Add .NET hebe implementation
wulkanowy/uonet-request-signer pull request #21
Opened 2020-12-16 14:03 UTC by MRmlik12

2020-12-25 13:06 UTC, mklkj requested changes
Please also rebase your branch

2020-12-25 13:06 UTC, mklkj commented on hebe-dotnet/UonetRequestSignerHebe/Signer.cs
> +        public SignerValues GetSignatureValues(string fingerprint, string privKey, string body, DateTime date, string path)
Please use the same args order as in other implementations (swap last two): https://github.com/wulkanowy/uonet-request-signer/blob/master/hebe-jvm/src/main/kotlin/signer.kt#L55-L60

2020-12-25 13:06 UTC, mklkj commented on hebe-dotnet/UonetRequestSignerHebe/Signer.cs
> +namespace UonetRequestSignerHebe
Change namespace to `Wulkanowy.UonetRequestSigner.Hebe

2020-12-26 21:08 UTC, MRmlik12 commented
Ok, I renamed solution to `Wulkanowy.UonetRequestSigner.Hebe` and updated `Signer.cs` args order. I deleted `SignerValues.cs` file because I used c# 7 feature it's called "value tuples".

2020-12-27 09:46 UTC, MRmlik12 commented
I modified Signer.cs with GetEncodedPath method to encode path properly

2020-12-27 11:32 UTC, mklkj requested changes

2020-12-27 11:32 UTC, mklkj commented on hebe-dotnet/README.md
> +var signed = new Signer().GetSignatureValues("fingerprint", "private_key", "body", "url", DateTime.Now);
One last thing - maybe make the `GetSignatureValues` method `static`? Similar to `dotnet` impl

2020-12-27 14:51 UTC, MRmlik12 commented on hebe-dotnet/README.md
> +var signed = new Signer().GetSignatureValues("fingerprint", "private_key", "body", "url", DateTime.Now);
I'll try make a static class If you want

2020-12-27 15:22 UTC, mklkj approved these changes

2020-12-27 15:22 UTC, merged